import { $, $$, button, slider, bindSlider, research, announce, session, fmt } from '../ui.js';
const roles={
  curious:{name:'Curious',steps:[['Arrive','Imagine a quiet room with a small box on a table. Your eyes can stay open.'],['Notice','Picture the edge of the box, a patch of light, and the table under your hand. Or describe them silently.'],['Meet a limit','The box is closed. You do not know what is inside. Let “I do not know yet” be an honest answer.'],['Try a process','Imagine asking one useful question: “May I look inside?” Practise the words slowly.'],['Allow a surprise','Perhaps the box is empty. Perhaps it holds something unexpected. Picture changing your idea when the answer changes.'],['Return','Look at the room you are really in. Choose one small question you could actually check.']]},
  patient:{name:'Patient',steps:[['Arrive','Imagine making a small bridge from paper. Keep your eyes open if you prefer.'],['Notice','Picture the fold, the light on the paper, and the quiet sound it makes. Words are fine if pictures are faint.'],['Meet a limit','The first fold slips. You may feel a little impatience in the imagined scene. You do not need to make the feeling strong.'],['Try a process','Imagine stopping your hand, looking at the fold, and changing just one part. Rehearse that small sequence.'],['Allow a surprise','The second try may still need work. Picture choosing whether to try again, rest, or ask for help.'],['Return','Look around your real room. Find one small task where a slower, clearer step might help.']]},
  kind:{name:'Kind',steps:[['Arrive','Imagine someone beside you trying to fit two puzzle pieces together. This is a made-up scene.'],['Notice','Picture the pieces and the space between you. You can think in words instead of pictures.'],['Meet a limit','You want to help, but you do not yet know what kind of help they want.'],['Try a process','Imagine asking, “Would you like a hand, or some space?” Rehearse waiting for their answer.'],['Allow a surprise','They may choose space. Picture respecting that answer while staying open to helping later.'],['Return','Look at where you really are. Think of one small, respectful offer you could make, if it is welcome.']]}
};
export function mount() {
  let role='curious',duration=60,current=0,active=null,finished=false;
  const ratings={};
  $('#stage').innerHTML=`<div class="stage-top"><strong>Rehearse a process, one small moment at a time.</strong><span id="imagine-time">1:00</span></div><div class="rehearsal-path" aria-hidden="true">${Array.from({length:6},(_,i)=>`<span data-path="${i}">${i+1}</span>`).join('')}</div><div class="center-scene" style="min-height:270px"><p class="eyebrow" id="imagine-step">Arrive</p><h2 id="imagine-prompt"></h2></div><div class="progress-track"><span id="imagine-progress"></span></div>`;
  $('#controls').innerHTML=`<h2>Which way would you like to practise?</h2><div class="button-row" role="group" aria-label="Way of being">${Object.entries(roles).map(([id,r])=>`<button type="button" class="choice" data-role="${id}" aria-pressed="${id===role}">${r.name}</button>`).join('')}</div><p class="small">This is an imagined practice, not a prediction or a memory. You do not need a vivid picture.</p><label class="field-label" for="imagine-length">Pace</label><select id="imagine-length"><option value="60">1 minute · 10 seconds per moment</option><option value="120">2 minutes · 20 seconds per moment</option><option value="180">3 minutes · 30 seconds per moment</option><option value="0">My own pace</option></select>${button('imagine-start','Begin imagining',true)}${button('imagine-next','Next moment')}${button('imagine-end','Return to the room')}<p class="small">Stay comfortable. Pause or finish if the scene feels distressing. Young children can imagine with a trusted grown-up.</p>`;
  $('#extra').innerHTML=`<details class="history"><summary>Notice the experience · optional</summary><p class="hint">Four different self-reports, not four ways to prove a scene is true. Leave them untouched to skip.</p><div class="imagery-rating">${[['detail','Picture or word detail'],['feeling','Feeling strength'],['real','How real it feels'],['belief','How possible it seems']].map(([id,label])=>`<div>${slider('rating-'+id,label,5,0,10,1,' / 10')}<p class="hint" id="rating-note-${id}">Not recorded</p></div>`).join('')}</div></details>`;
  for(const id of ['detail','feeling','real','belief'])bindSlider('rating-'+id,v=>{ratings[id]=v;$('#rating-note-'+id).textContent=`You report ${v}/10.`;},v=>`${v} / 10`);
  const paint=()=>{const [title,prompt]=roles[role].steps[current];$('#imagine-step').textContent=`${current+1} / 6 · ${title}`;$('#imagine-prompt').textContent=prompt;$$('[data-path]').forEach(n=>n.classList.toggle('current',Number(n.dataset.path)===current));};
  const end=complete=>{
    if(finished)return;finished=true;const elapsed=active?.clock.elapsed||0;active?.dispose();active=null;
    $('#imagine-time').textContent=complete?'Sequence complete':'Finished early';$('#imagine-step').textContent='Here, now';$('#imagine-prompt').textContent='Look around your real room. Let the imagined scene end.';
    $('#controls').innerHTML=`<h2>${complete?'You rehearsed a way of responding.':'You chose to return.'}</h2><p>${duration?`${fmt(elapsed)} of timed practice. `:'You moved at your own pace. '}Imagining ${roles[role].name.toLowerCase()} action is different from doing it.</p><p>Choose a small way to check a next step:</p><div class="choice-list"><button class="choice" data-next="clue">Ask for one useful clue.</button><button class="choice" data-next="try">Try one small, reversible action.</button><button class="choice" data-next="wait">Pause and watch what happens.</button></div>${button('imagine-again','Try another way')}`;
    const responses={clue:'What observation would change your idea? Keep the question small enough to answer.',try:'What result would you look for? Decide before trying, then compare with what happens.',wait:'What are you waiting to learn, and when will you look again? A pause can have a purpose.'};
    $$('[data-next]').forEach(b=>b.addEventListener('click',()=>{$$('[data-next]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));announce(responses[b.dataset.next]+' You have selected a possible action; the page cannot know whether you carried it out.');}));$('#imagine-again').addEventListener('click',mount);
    announce(complete?'The six imagined moments are complete. Picture strength, belief and real-world evidence remain different things.':'The rehearsal ended early. Your comfort matters more than finishing a timer.');
  };
  const lock=()=>{$$('[data-role]').forEach(b=>b.disabled=true);$('#imagine-length').disabled=true;$('#imagine-end').hidden=false;};
  $$('[data-role]').forEach(b=>b.addEventListener('click',()=>{role=b.dataset.role;$$('[data-role]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));paint();announce(`A ${roles[role].name.toLowerCase()} way of responding. This is a practice choice, not a personality label.`);}));
  $('#imagine-length').addEventListener('change',()=>{duration=Number($('#imagine-length').value);$('#imagine-time').textContent=duration?fmt(duration):'At your pace';});
  $('#imagine-start').addEventListener('click',()=>{
    if(active){if(active.clock.running)active.pause();else active.play();return;}
    lock();
    if(duration===0){$('#imagine-start').hidden=true;$('#imagine-next').hidden=false;announce(roles[role].steps[current][1]);return;}
    let last=-1;
    active=session(duration,clock=>{current=Math.min(5,Math.floor(clock.elapsed/duration*6));$('#imagine-time').textContent=fmt(duration-clock.elapsed);$('#imagine-progress').style.width=`${clock.elapsed/duration*100}%`;$('#imagine-start').textContent=clock.running?'Pause':'Resume imagining';if(current!==last){last=current;paint();announce(roles[role].steps[current][1]);}},()=>end(true));active.play();
  });
  $('#imagine-next').addEventListener('click',()=>{if(current===5){end(true);return;}current++;paint();$('#imagine-progress').style.width=`${current/6*100}%`;$('#imagine-next').textContent=current===5?'Finish the sequence':'Next moment';announce(roles[role].steps[current][1]);});
  $('#imagine-end').addEventListener('click',()=>end(false));$('#imagine-next').hidden=true;$('#imagine-end').hidden=true;paint();announce('Choose a way to practise. You can use words, pictures, or a simple sense of the scene.');
  research({question:'Can an imagined future change a next action?',finding:'In an experiment with students, process-focused mental simulation supported studying and exam performance through planning and anxiety changes. That result concerns a particular task, not a general law that vivid thought creates reality.',model:'Each authored scene moves through context, sensory detail, an obstacle, a response, an alternative outcome and return to the present. Ten-second segments are the short design option, not a validated dose. The optional ratings separate detail, emotion, felt realness and plausibility. A final action choice is recorded only as a choice.',limits:'These scenes have not been evaluated as a treatment or a way to change personality. Imagery need not be vivid; people can use words. Rehearsal is neither a recovered memory nor evidence that an event happened or will happen. Belief and feeling cannot substitute for observation.',sources:[['Pham & Taylor (1999) · From thought to action: process versus outcome simulation','https://journals.sagepub.com/doi/10.1177/0146167299025002010']]});
}
